[package]
name = "rust_project"
version = "0.1.0"
edition = "2021"

[dependencies]
color-print = "0.3.6"
gethostname = "0.5.0"

[[bin]]
name = "colo_print"
path = "src/main.rs"
test = false
doctest = false
bench = false
